### ISSUE TITLE
 space engineers dedicated server port forwarding

### ISSUE THREAD

**Issue by blindguy** [Devidian/docker-spaceengineers#41]
Not so much of a bug issue but a how do I question.
I have things running fine and can connect from inside my network but not from anything external.
I tried using a custom published port and then fordwarding that port on my router but that didn't work.
    ports:
      - target: 27016
        published: 40101
        protocol: udp
        mode: host

I then set both to 27016 and then set up my router to forward 20716 to that machine and that also did not work.  

I have other games working like this but not sure what is wrong here.  Di I need more than one port open on the router?
Thanks

**Comment by Devidian** [comment]
Hi there, that issue is a bit difficult as it depends on your connection. For example i cant host any game server on lan for external connections on most games, as i only have a pseudo ipv4 (DS-Lite-Tunnel).  I would have to use some tools for that if i wanted to achieve that.

In a normal case the published port should be enought.
